import {chromium} from 'playwright';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {inflateSync} from 'node:zlib';
import {fromArrayBuffer} from 'geotiff';
import {existsSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const shotDir=process.env.CI?'artifacts/ci-screenshots':'artifacts/screenshots';
const reportPath=path.join(root,process.env.CI?'evaluation/checks/browser-smoke-ci.json':'evaluation/checks/browser-smoke.json');
await mkdir(path.join(root,shotDir),{recursive:true});
const executable=process.env.NUCLEILENS_CHROMIUM_BIN||(!process.env.CI&&existsSync('/usr/bin/chromium')?'/usr/bin/chromium':undefined);
const browser=await chromium.launch({executablePath:executable,headless:true,args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1440,height:1080}});
const errors=[];const failedRequests=[];const consoleErrors=[];const nonReadRequests=[];page.on('requestfailed',r=>failedRequests.push({path:new URL(r.url()).pathname,error:r.failure()?.errorText}));page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text().slice(0,500));});page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!['GET','HEAD','OPTIONS'].includes(r.method())){const url=new URL(r.url());nonReadRequests.push({method:r.method(),origin:url.origin,path:url.pathname.startsWith('/cdn-cgi/challenge-platform/')?'/cdn-cgi/challenge-platform/':url.pathname});}});
const target=process.env.NUCLEILENS_DEMO_URL||'http://127.0.0.1:5173';
try {
await page.goto(target);
await page.getByRole('button',{name:'Rerun on this device'}).waitFor();
await page.waitForFunction(()=>document.querySelector('.count-strip strong')?.textContent!=='—');
const additionalSection=page.getByRole('region',{name:'Additional assessment'});
await additionalSection.waitFor();
if(!(await additionalSection.textContent()).includes('496 evaluated, 0 failures')||!(await additionalSection.textContent()).includes('45.7%'))throw new Error('Additional evidence did not render the frozen results');
await page.getByRole('button',{name:/Inspect split/}).click();
await page.waitForFunction(()=>document.querySelector('#alternative')?.value==='1');
await page.getByRole('button',{name:'Full field'}).click();
await page.screenshot({path:path.join(root,shotDir,'desktop.png'),fullPage:true});
await page.getByRole('button',{name:'Inspect split · 1 → 2'}).click();
await page.getByRole('button',{name:'Confirm split alternative · 1 → 2'}).click();
await page.waitForFunction(()=>document.querySelector('[data-testid=mask-count]')?.textContent?.startsWith('75 '));
if(!(await page.locator('.mask-review [role=status]').textContent()).includes('Review tally total remains 74'))throw new Error('Split feedback did not explain the independent tally');
await page.getByRole('button',{name:'Inspect merge · 2 → 1'}).click();
await page.getByRole('button',{name:'Confirm merge alternative · 2 → 1'}).click();
await page.waitForFunction(()=>document.querySelector('[data-testid=mask-count]')?.textContent?.startsWith('74 '));
if(!(await page.locator('.mask-review [role=status]').textContent()).includes('Review tally total remains 74'))throw new Error('Merge feedback did not explain the independent tally');
const labelDownload=page.waitForEvent('download');await page.getByRole('button',{name:'Export label TIFF'}).click();await(await labelDownload).saveAs(path.join(root,'artifacts/mask-edit-smoke.tif'));
const exported=await readFile(path.join(root,'artifacts/mask-edit-smoke.tif'));const tiff=await fromArrayBuffer(exported.buffer.slice(exported.byteOffset,exported.byteOffset+exported.byteLength));const labelImage=await tiff.getImage();const labels=await labelImage.readRasters({interleave:true});
if(!(labels instanceof Uint32Array)||new Set(Array.from(labels).filter(id=>id!==0)).size!==74)throw new Error('Exported mask is not a 74-instance uint32 label map');
const reference=JSON.parse(await readFile(path.join(root,'frontend/public/samples/training-001.json'),'utf8'));const baselineBytes=inflateSync(Buffer.from(reference.label_maps.runs[0],'base64'));const labelBytes=Buffer.alloc(labels.length*4);labels.forEach((id,i)=>labelBytes.writeUInt32LE(id,i*4));
if(labelBytes.equals(baselineBytes))throw new Error('Same-total edit did not change pixels');
const maskAuditDownload=page.waitForEvent('download');await page.getByRole('button',{name:'Export review JSON'}).click();await(await maskAuditDownload).saveAs(path.join(root,'artifacts/mask-edit-audit-smoke.json'));
const maskAudit=JSON.parse(await readFile(path.join(root,'artifacts/mask-edit-audit-smoke.json'),'utf8'));if(maskAudit.mask_review.sha256_uint32_le!==createHash('sha256').update(labelBytes).digest('hex')||maskAudit.mask_review.changes.length!==2||!maskAudit.mask_modifications)throw new Error('Mask audit does not match exported labels');
await page.getByRole('button',{name:'Full field'}).click();await page.screenshot({path:path.join(root,shotDir,'mask-edits.png'),fullPage:true});
const before=await page.locator('.count-strip strong').last().textContent();
const count=await page.locator('#count').inputValue();
await page.locator('#count').fill(String(Number(count)+1));
await page.getByRole('button',{name:'Confirm region'}).click();
const after=await page.locator('.count-strip strong').last().textContent();
if(Number(after)!==Number(before)+1)throw new Error('Review total did not update');
const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export review JSON'}).click();await(await download).saveAs(path.join(root,'artifacts/review-audit-smoke.json'));
await page.getByRole('button',{name:'Undo',exact:true}).click();
if(await page.locator('.count-strip strong').last().textContent()!==before) throw new Error('Undo failed');
await page.locator('#alternative').selectOption('3');
await page.getByRole('button',{name:'Zoom to region'}).click();
await page.screenshot({path:path.join(root,shotDir,'review-detail.png')});
await page.getByRole('button',{name:'Full field'}).click();
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:path.join(root,shotDir,'mobile.png'),fullPage:true});
if(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth))throw new Error('Mobile overflow');
await page.setViewportSize({width:1440,height:1080});
await page.locator('#count').fill(String(Number(await page.locator('#count').inputValue())+1));
await page.getByRole('button',{name:'Confirm region'}).click();
const preservedTotal=await page.locator('.count-strip strong').last().textContent();
const coldStarted=performance.now();
await page.getByRole('button',{name:'Rerun on this device'}).click();
await page.waitForFunction(()=>document.querySelector('.status-row')?.textContent?.includes('Analysis completed on your device.') || !!document.querySelector('[role=alert]'),{},{timeout:100000});
if(await page.locator('[role=alert]').count()) throw new Error(await page.locator('[role=alert]').textContent());
const coldMs=performance.now()-coldStarted;
const result=await page.locator('.count-strip strong').first().textContent();
if(Number(result)!==74)throw new Error('Browser/native sample parity failed');
if(await page.locator('.count-strip strong').last().textContent()!==preservedTotal)throw new Error('Compatible human review was lost on rerun');
const warmStarted=performance.now();
await page.getByRole('button',{name:'Rerun on this device'}).click();
await page.waitForFunction(()=>document.querySelector('.status-row')?.textContent?.includes('Analysis completed on your device.') || !!document.querySelector('[role=alert]'),{},{timeout:100000});
if(await page.locator('[role=alert]').count())throw new Error(await page.locator('[role=alert]').textContent());
const warmMs=performance.now()-warmStarted;
const repeatedDownload=page.waitForEvent('download');await page.getByRole('button',{name:'Export label TIFF'}).click();await(await repeatedDownload).saveAs(path.join(root,'artifacts/mask-rerun-smoke.tif'));
if(!(await readFile(path.join(root,'artifacts/mask-rerun-smoke.tif'))).equals(exported))throw new Error('Compatible mask edits were lost on rerun');
await page.getByRole('button',{name:'Undo mask edit'}).click();await page.getByRole('button',{name:'Undo mask edit'}).click();
if(!await page.getByRole('button',{name:'Undo mask edit'}).isDisabled())throw new Error('Mask undo history did not clear');
if(!(await page.locator('.mask-review [role=status]').textContent()).includes('Review tally total remains'))throw new Error('Undo feedback did not explain the independent tally');
const restoredDownload=page.waitForEvent('download');await page.getByRole('button',{name:'Export label TIFF'}).click();await(await restoredDownload).saveAs(path.join(root,'artifacts/mask-restored-smoke.tif'));
const restored=await readFile(path.join(root,'artifacts/mask-restored-smoke.tif'));const restoredImage=await(await fromArrayBuffer(restored.buffer.slice(restored.byteOffset,restored.byteOffset+restored.byteLength))).getImage();const restoredLabels=await restoredImage.readRasters({interleave:true});const restoredBytes=Buffer.alloc(restoredLabels.length*4);restoredLabels.forEach((id,i)=>restoredBytes.writeUInt32LE(id,i*4));if(!restoredBytes.equals(baselineBytes))throw new Error('Undo did not restore exact baseline pixels');
await page.getByRole('button',{name:'Rerun on this device'}).click();await page.getByRole('button',{name:'Cancel',exact:true}).click();
await page.waitForFunction(()=>document.querySelector('.status-row')?.textContent?.includes('Analysis cancelled.'));
if(Number(await page.locator('.count-strip strong').first().textContent())!==74)throw new Error('Cancel discarded the usable reference analysis');
await page.route('**/samples/training-002.json',async route=>{await new Promise(resolve=>setTimeout(resolve,1500));await route.abort('failed');});
await page.getByRole('button',{name:'Dense field BBBC039'}).click();await page.getByRole('button',{name:'Cancel',exact:true}).click();
await page.getByRole('button',{name:'First training field BBBC039'}).click();await page.waitForTimeout(1800);
if(await page.locator('[role=alert]').count())throw new Error('Stale sample failure affected a newer request');
await page.unroute('**/samples/training-002.json');
await page.screenshot({path:path.join(root,shotDir,'live-analysis.png'),fullPage:true});
await mkdir(path.join(root,'evaluation/checks'),{recursive:true});
await writeFile(reportPath,JSON.stringify({status:'passed',generated_at:new Date().toISOString(),target,review_update:true,undo:true,audit_export:true,same_count_witness:true,additional_evidence_rendered:true,review_preserved_on_rerun:true,mask_split_merge_counts:[74,75,74],mask_tiff_roundtrip:true,mask_audit_hash_verified:true,mask_preserved_on_rerun:true,mask_undo_exact:true,cancel_preserves_reference:true,stale_sample_failure_ignored:true,mobile_overflow:false,live_analysis_count:Number(result),cold_browser_ms:Math.round(coldMs),warm_browser_ms:Math.round(warmMs),non_read_requests:nonReadRequests,page_errors:errors},null,2));
if(errors.length)throw new Error(errors.join('\n'));
console.log('PASS: review, undo, audit, mobile, actual browser-local analysis. Count '+result);

} catch(error) {
 await mkdir(path.join(root,'evaluation/checks'),{recursive:true});
 await writeFile(reportPath,JSON.stringify({status:'failed',generated_at:new Date().toISOString(),target,error:String(error),visible_status:await page.locator('.status-row').textContent().catch(()=>null),page_errors:errors,console_errors:consoleErrors,failed_requests:failedRequests},null,2));
 await page.screenshot({path:path.join(root,shotDir,'failure.png'),fullPage:true}).catch(()=>{});
 throw error;
} finally {await browser.close();}
