import {chromium} from 'playwright';
import {mkdir,writeFile} from 'node:fs/promises';
import {existsSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
await mkdir(path.join(root,'artifacts/screenshots'),{recursive:true});
const executable=process.env.NUCLEILENS_CHROMIUM_BIN||(existsSync('/usr/bin/chromium')?'/usr/bin/chromium':undefined);
const browser=await chromium.launch({executablePath:executable,headless:true,args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1440,height:1080}});
const errors=[];const nonReadRequests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!['GET','HEAD','OPTIONS'].includes(r.method()))nonReadRequests.push({method:r.method(),url:r.url()});});
const target=process.env.NUCLEILENS_DEMO_URL||'http://127.0.0.1:5173';
await page.goto(target);
await page.getByRole('button',{name:'Rerun on this device'}).waitFor();
await page.waitForFunction(()=>document.querySelector('.count-strip strong')?.textContent!=='—');
await page.getByRole('button',{name:/Inspect split/}).click();
await page.waitForFunction(()=>document.querySelector('#alternative')?.value==='1');
await page.getByRole('button',{name:'Full field'}).click();
await page.screenshot({path:path.join(root,'artifacts/screenshots/desktop.png'),fullPage:true});
const before=await page.locator('.count-strip strong').last().textContent();
const count=await page.locator('#count').inputValue();
await page.locator('#count').fill(String(Number(count)+1));
await page.getByRole('button',{name:'Confirm region'}).click();
const after=await page.locator('.count-strip strong').last().textContent();
if(Number(after)!==Number(before)+1)throw new Error('Review total did not update');
const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export review JSON'}).click();await(await download).saveAs(path.join(root,'artifacts/review-audit-smoke.json'));
await page.getByRole('button',{name:'Undo',exact:true}).click();
if(await page.locator('.count-strip strong').last().textContent()!==before) throw new Error('Undo failed');
await page.locator('#alternative').selectOption('3');
await page.getByRole('button',{name:'Zoom to region'}).click();
await page.screenshot({path:path.join(root,'artifacts/screenshots/review-detail.png')});
await page.getByRole('button',{name:'Full field'}).click();
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:path.join(root,'artifacts/screenshots/mobile.png'),fullPage:true});
if(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth))throw new Error('Mobile overflow');
await page.setViewportSize({width:1440,height:1080});
await page.locator('#count').fill(String(Number(await page.locator('#count').inputValue())+1));
await page.getByRole('button',{name:'Confirm region'}).click();
const preservedTotal=await page.locator('.count-strip strong').last().textContent();
const coldStarted=performance.now();
await page.getByRole('button',{name:'Rerun on this device'}).click();
await page.waitForFunction(()=>document.querySelector('.status-row')?.textContent?.includes('Analysis completed on your device.') || !!document.querySelector('[role=alert]'),{},{timeout:100000});
if(await page.locator('[role=alert]').count()) throw new Error(await page.locator('[role=alert]').textContent());
const coldMs=performance.now()-coldStarted;
const result=await page.locator('.count-strip strong').first().textContent();
if(Number(result)!==74)throw new Error('Browser/native sample parity failed');
if(await page.locator('.count-strip strong').last().textContent()!==preservedTotal)throw new Error('Compatible human review was lost on rerun');
const warmStarted=performance.now();
await page.getByRole('button',{name:'Rerun on this device'}).click();
await page.waitForFunction(()=>document.querySelector('.status-row')?.textContent?.includes('Analysis completed on your device.') || !!document.querySelector('[role=alert]'),{},{timeout:100000});
if(await page.locator('[role=alert]').count())throw new Error(await page.locator('[role=alert]').textContent());
const warmMs=performance.now()-warmStarted;
await page.screenshot({path:path.join(root,'artifacts/screenshots/live-analysis.png'),fullPage:true});
await mkdir(path.join(root,'evaluation/checks'),{recursive:true});
await writeFile(path.join(root,'evaluation/checks/browser-smoke.json'),JSON.stringify({generated_at:new Date().toISOString(),target,review_update:true,undo:true,audit_export:true,same_count_witness:true,review_preserved_on_rerun:true,mobile_overflow:false,live_analysis_count:Number(result),cold_browser_ms:Math.round(coldMs),warm_browser_ms:Math.round(warmMs),non_read_requests:nonReadRequests,page_errors:errors},null,2));
await browser.close();if(errors.length)throw new Error(errors.join('\n'));
console.log('PASS: review, undo, audit, mobile, actual browser-local analysis. Count '+result);
