/* Integrity/coverage check on the three declared training demo fields, not accuracy. */
import{readFile,writeFile}from'node:fs/promises';import{createHash}from'node:crypto';import{decodeLabelMaps,applyMaskProposal,undoMaskPatch}from'../frontend/src/masks.ts';
const hash=data=>createHash('sha256').update(data).digest('hex');const manifest=JSON.parse(await readFile('frontend/public/samples/manifest.json','utf8'));const fields=[];
for(const sample of manifest.samples){
 const bytes=await readFile('frontend/public'+sample.analysis_url),analysis=JSON.parse(bytes);const masks=await decodeLabelMaps(analysis);let accepted=0;const rejected=[];
 for(const region of analysis.regions)for(const event of region.events){try{const changed=applyMaskProposal(masks[0],masks[0],masks[event.run_id],event);const restored=undoMaskPatch(changed.mask,changed.patch);if(!Buffer.from(restored.buffer).equals(Buffer.from(masks[0].buffer)))throw Error('Undo integrity failed');accepted++;}catch(error){const reason=String(error.message);if(!reason.includes('overlaps a retained nucleus'))throw error;rejected.push({region_id:region.id,run_id:event.run_id,kind:event.kind,reason});}}
 fields.push({sample:sample.id,selection_note:sample.note,analysis_sha256:hash(bytes),accepted_independent_proposals:accepted,rejected_conflicting_proposals:rejected.length,rejections:rejected});
}
const report={generated_at:new Date().toISOString(),scope:'Three declared training demo fields, selected as first, second and lowest-F1 among first eight. Independent proposals against the original baseline; not sequential editing coverage, biological correctness or human benefit.',source_sha256:hash(await readFile('frontend/src/masks.ts')),fields};await writeFile('evaluation/checks/mask-proposal-integrity.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(fields.map(({sample,accepted_independent_proposals,rejected_conflicting_proposals})=>({sample,accepted_independent_proposals,rejected_conflicting_proposals}))));
